config/routes.rb
require 'sidekiq/web'

Rails.application.routes.draw do
  #use_doorkeeper
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html

  # sidekiq Routes
  mount Sidekiq::Web => '/sidekiq'

  # api routes
    #namespace :api do
  #  namespace :v1 do
      #
      # oauth2 implementation routes for grant password and refresh_token
      #
  #    resources :sessions, only: [:create, :update], param: :token
  #  end
  #end
  mount Api::Base => '/'

  # web socket server
  mount ActionCable.server => '/cable'

  # root path
  root to: 'home#index'

  # account's routes

  devise_for :accounts, path: 'auth', skip: [:registrations, :passwords], class_name: "Users::Models::Account",
             path_names: {sign_in: 'login', sign_out: 'logout',},
             controllers: {sessions: 'sessions',}

  # custom token login
  devise_scope :account do
    get 'sessions/token', to: "sessions#token", as: :token_session_account
  end

  namespace :ripple do
    resources :wallets do
      member do
        put :active
        put :restore
        put :secret
      end
      collection do
        unless Rails.env.production?
          post :generate_xrp_testnet_wallet
        end
      end
      resources :transactions, only: [:new, :create] do
        member do
          put :complete
        end
      end
    end
    resources :export_secrets, only: :show, path: "secrets" do
      member { put(:decrypt) }
    end
  end

  resources :plans, only: [:index], param: :name do
    resources :subscriptions, only: [:new, :create, :show], param: :name do
      member do
        put :cancel
      end
    end
  end

  resources :pins, only: [:update]

  resources :settings, path: "setting", only: [:index] do
    collection do
      put :update
    end
  end

  # static pages
  get "/pages/*page" => "pages#show", as: :page

  # admin's routes

  devise_for :admins, path: "administrator", skip: [:confirmations, :registrations], class_name: "Administration::Models::Admin",
              path_names: { sign_in: "login", sign_out:  "logout"},
              controllers: { sessions: "admin/sessions", passwords: "admin/profile" }

  namespace :admin, path: "administrator" do

    get "", to: "dashboards#index"

    resources :dashboards, path: "dashboard", only: :index do
      collection do
        get :accounts
        get :subscriptions
      end
    end
    resources :accounts, only: [:index, :show], param: :username
    resources :plans, path: "packages", param: :name do
      member do
        put :activate
        put :deactivate
      end
    end
    resources :subscriptions, only: [:index, :show], param: :name do
      member do
        put :cancel
        put :confirm
        put :expire
      end
    end

    resources :profiles, path: "profile", only: [:edit, :update]

    resources :transactions, only: [:index, :show]
    resources :wallets, only: [:index, :show]

  end


end

app/controllers/home_controller.rb
class HomeController < ApplicationController

  def index
    
  end

end

app/views/home/index.html.erb
<%= yield_content_for(:title, "Home") %>

<% unless current_account %>

  <% unless Rails.env.production? %>
    <%= content_tag :div, class: 'row' do %>
      <%= content_tag :div, class: "col-md-8 col-md-offset-2" do %>
        <%= box_panel style: "box-warning box-solid" do |panel| %>

          <%= _content_for(panel, :box_panel_body) do %>
            <%= content_tag :p, "use mailinator to generate email for testing. eg: user@mailinator. then head to <a href='https://www.mailinator.com/v2/inbox.jsp?zone=public&query=user'>https://www.mailinator.com/v2/inbox.jsp?zone=public&query=user</a> to get login url".html_safe, class: "help-block text-center" %>
          <%- end %>

        <%- end %>
      <%- end %>
    <%- end %>
  <%- end %>

  <%= content_tag :div, class: 'col-md-4 col-md-offset-4' do %>
    
    <%= content_tag :div, class: 'text-center' do %>
      <%= content_tag :h3, "Register/Login" %>
    <%- end %>

    <%= content_tag :div, class: "row" do %>

      <%= box_panel do |panel| %>
        
        <%= _content_for panel, :box_panel_body do %>
          <%= content_tag :p, "Sign in to start your session", class: 'login-box-msg' %>

          <%= form_for(devise_resource, as: :account, url: account_session_path()) do |f| %>
            
            <%= form_group devise_resource, :login, options={ strict: false} do %>
              <%= f.email_field :email, class: 'form-control', placeholder: 'Your email' %>
              <%= content_tag :span, '', class: 'glyphicon glyphicon-envelope form-control-feedback' %>
            <%- end %>

            <% form_group devise_resource, :login, options={ strict: false} do %>
              <%= f.text_field :login, class: 'form-control', placeholder: 'Your email' %>
              <%= content_tag :span, '', class: 'glyphicon glyphicon-envelope form-control-feedback' %>
            <%- end %>

            <% form_group devise_resource, :password, options={ strict: false } do %>
              <%= f.password_field :password, class: 'form-control', placeholder: 'Password' %>
              <%= content_tag :span, '', class: 'glyphicon glyphicon-lock form-control-feedback' %>
            <%- end %>

            <%= content_tag :div, class: 'row' do %>
              <% content_tag :div, class: 'col-xs-8' do %>
                <%= content_tag :div, class: 'checkbox icheck' do %>
                  <%= content_tag :label do %>
                    <%= f.check_box :remember_me %> Remember Me
                  <%- end %>
                <%- end %>
              <%- end %>
              <%= content_tag :div, class: 'col-xs-4' do %>
                <%= f.submit "Sign In", class: 'btn btn-primary btn-block btn-flat' %>
              <%- end %>
            <%- end %>
          <%- end %>
        <%- end %>

      <%- end %>

    <%- end %>

  <%- end %>

<%- end %>