config/routes.rb
require 'sidekiq/web'

Rails.application.routes.draw do
  #use_doorkeeper
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html

  # sidekiq Routes
  mount Sidekiq::Web => '/sidekiq'

  # api routes
    #namespace :api do
  #  namespace :v1 do
      #
      # oauth2 implementation routes for grant password and refresh_token
      #
  #    resources :sessions, only: [:create, :update], param: :token
  #  end
  #end
  mount Api::Base => '/'

  # web socket server
  mount ActionCable.server => '/cable'

  # root path
  root to: 'home#index'

  # account's routes

  devise_for :accounts, path: 'auth', skip: [:registrations, :passwords], class_name: "Users::Models::Account",
             path_names: {sign_in: 'login', sign_out: 'logout',},
             controllers: {sessions: 'sessions',}

  # custom token login
  devise_scope :account do
    get 'sessions/token', to: "sessions#token", as: :token_session_account
  end

  namespace :ripple do
    resources :wallets do
      member do
        put :active
        put :restore
        put :secret
      end
      collection do
        unless Rails.env.production?
          post :generate_xrp_testnet_wallet
        end
      end
      resources :transactions, only: [:new, :create] do
        member do
          put :complete
        end
      end
    end
    resources :export_secrets, only: :show, path: "secrets" do
      member { put(:decrypt) }
    end
  end

  resources :plans, only: [:index], param: :name do
    resources :subscriptions, only: [:new, :create, :show], param: :name do
      member do
        put :cancel
      end
    end
  end

  resources :pins, only: [:update]

  resources :settings, path: "setting", only: [:index] do
    collection do
      put :update
    end
  end

  # static pages
  get "/pages/*page" => "pages#show", as: :page

  # admin's routes

  devise_for :admins, path: "administrator", skip: [:confirmations, :registrations], class_name: "Administration::Models::Admin",
              path_names: { sign_in: "login", sign_out:  "logout"},
              controllers: { sessions: "admin/sessions", passwords: "admin/profile" }

  namespace :admin, path: "administrator" do

    get "", to: "dashboards#index"

    resources :dashboards, path: "dashboard", only: :index do
      collection do
        get :accounts
        get :subscriptions
      end
    end
    resources :accounts, only: [:index, :show], param: :username
    resources :plans, path: "packages", param: :name do
      member do
        put :activate
        put :deactivate
      end
    end
    resources :subscriptions, only: [:index, :show], param: :name do
      member do
        put :cancel
        put :confirm
        put :expire
      end
    end

    resources :profiles, path: "profile", only: [:edit, :update]

    resources :transactions, only: [:index, :show]
    resources :wallets, only: [:index, :show]

  end


end

app/controllers/admin/wallets_controller.rb
module Admin
  class WalletsController < AdminController

    self.context_resource_class= "Ripples::Models::Wallet"
    self.resource_actions = [:show]
    use_resource!
  
    def index
      @wallets = Ripples::Models::Wallet.filter(filter_params.merge!(archived: params[:archived])).page(params[:page]).per(20)
      respond_to do |f|
        f.html
        f.js do 
          render_table
        end
      end
    end

    def show
      respond_to do |f|
        f.html
        f.js {
          if modal_params_present?
            render_modal
          end
        }
      end
    end

  end
end

app/controllers/ripple/wallets_controller.rb
require 'connection/request'

module Ripple
  class WalletsController < AccountController

    self.context_resource_class= "Ripples::Models::Wallet"
    self.resource_actions = [:new, :create, :edit, :update, :show, :destroy, :active, :secret]
    use_resource!

    include Users::Helpers::SubscriptionRestriction::Controller

    def index
      if params[:archived]
        @wallets = resource_class_constant.deleted
      else
        @wallets = resource_class_constant
      end
      @wallets = @wallets.where(account: current_account).order("updated_at DESC").page(params[:page]).per(20)
      respond_to do |f|
        f.html
        f.js do
          render_table
        end
      end
    end

    def show
      respond_to do |f|
        f.html
        f.js {
          if modal_params_present?
            render_modal
          end
        }
      end
    end

    def create
      restrict_address_creation do
        @wallet.account = current_account
        if @wallet.save
          respond_to do |f|
            f.html { redirect_to ripple_wallets_path, notice: "Success" }
            f.js do
              params[:notification]= { message: "Wallet created!" }
              render_table "/shared/table/reload.js.erb"
            end
          end
        else
          respond_to do |f|
            f.html { render :new }
            f.js do
              if modal_params_present?
                params[:notification]= { message: "Failed to create wallet!", type: "danger" }
                render_modal
              end
            end
          end
        end
      end
    end

    def new
      respond_to do |f|
        f.html
        f.js {
          if modal_params_present?
            render_modal
          end
        }
      end
    end

    def edit
      respond_to do |f|
        f.html
        f.js {
          if modal_params_present?
            render_modal
          end
        }
      end
    end

    def update
      if @wallet.update wallet_params
        respond_to do |f|
          f.html { redirect_to ripple_wallets_path, notice: "Success" }
          f.js do
            params[:notification]= { message: "Wallet updated!" }
            render_table "/shared/table/reload.js.erb"
          end
        end
      else
        respond_to do |f|
          f.html { render :new }
          f.js do
            if modal_params_present?
              params[:notification]= { message: "Failed to update wallet!", type: "danger" }
              render_modal
            end
          end
        end
      end
    end

    def destroy
      if @wallet.destroy
        respond_to do |f|
          f.html { redirect_to ripple_wallets_path, notice: "Wallet is archived!" }
          f.js do
            if table_params_present?
              params[:notification]= { message: "Wallet is sent to archive" }
              render_table "/shared/table/reload.js.erb"
            end
          end
        end
      end
    end

    def active
      @wallet.update(validated: true)
      respond_to do |f|
        f.html { redirect_to ripple_wallets_path, notice: "Wallet is validated." }
        f.js{  }
      end
    end

    def restore
      if resource_class_constant.restore(params[:id])
        respond_to do |f|
          f.html{ redirect_to ripple_wallets_path(archived: true), notice: "Wallet is restored" }
          f.js do
            if table_params_present?
              params[:notification]= { message: "Wallet restored!" }
              render_table "/shared/table/reload.js.erb"
            end
          end
        end
      else
      end
    end

    def generate_xrp_testnet_wallet
      connection = ::Connection::Request.new :post, "https://faucet.altnet.rippletest.net/accounts", {}, true
      connection.invoke
      if connection.success?
        wallet = resource_class_constant.create!(
                                                  address: connection.response.account.address,
                                                  secret: connection.response.account.secret,
                                                  balance: BigDecimal.new(connection.response.balance) * 1000000,
                                                  validated: true,
                                                  account: current_account,
                                                  skip_generate_address: true
                                                )
        respond_to do |f|
          message = "Wallet is successfully created."
          f.html { redirect_to ripple_wallets_path, notice: message }
          f.js {
            render_table "/shared/table/reload.js.erb"
          }
        end
      else
        message = "Connection failure."
        respond_to do |f|
          f.html { redirect_to ripple_wallets_path, error: message }
          f.js {
            params[:notification] = { message: message, type: "error" }
            dismiss_modal
          }
        end
      end
    end

    def secret
      encrypted_request = @wallet.create_encrypted_request_for :secret
      if encrypted_request.persisted?
        message = "Instruction for exporting your address's secret is sent to your email."
        respond_to do |f|
          f.html{
            flash[:notice]= message
            redirect_back(fallback_location: root_path)
          }
          f.js{
            params[:notification]= { message: message }
            render_notification
          }
        end
      else
        message = "Failed!"
        respond_to do |f|
          f.html{
            flash[:notice]= message
            redirect_back(fallback_location: root_path)
          }
          f.js{
            params[:notification]= { message: message, type: "error" }
            render_notification
          }
        end
      end
    end

    def wallet_params
      if params[:ripples_models_wallet].present?
        params.require(:ripples_models_wallet).permit(:label)
      end
    end

  end
end

app/views/admin/wallets/_filter.html.erb
<%= content_tag :div, class: "row" do %>
    
  <%= content_tag :div, class: "col-md-6" do %>
    
    <%= form_group_tag :address, { label_class: "col-sm-3" } do %>
      <%= text_field_tag "filter[address]", filter_params[:name], class: 'form-control', placeholder: 'Filter by address' %>
    <%- end %>

    <%= form_group_tag :label, { label_class: "col-sm-3" } do %>
      <%= text_field_tag "filter[label]", filter_params[:name], class: 'form-control', placeholder: 'Filter by label name' %>
    <%- end %>

  <%- end %>

  <%= content_tag :div, class: "col-md-6" do %>
    
    <%= form_group_tag :status, { label_class: "col-sm-3" } do %>
      <%= select_tag 'filter[wallet_type]', options_for_select(["Cold", "Hot"]), prompt: "Filter by wallet status", class: "form-control" %>
    <%- end %>

    <%= form_group_tag :updated_to, { label_class: "col-sm-3" } do %>
      <%= text_field_tag 'filter[to_time]', filter_params[:to_time], class: 'form-control pick-a-date', placeholder: 'Set date' %>
    <%- end %>

    <%= form_group_tag :updated_from, { label_class: "col-sm-3" } do %>
      <%= text_field_tag 'filter[from_time]', filter_params[:from_time], class: 'form-control pick-a-date', placeholder: 'Set date' %>
    <%- end %>

  <%- end %>

<%- end %>

app/views/admin/wallets/_table.html.erb
  <%= content_tag :table, class: 'table table-hover', id: "wallets" do %>
    <%= content_tag :thead do %>
      <%= content_tag :tr do %>
        <% ["Sequence","Label", "Address", "Status", "Balance", "Pending Received", "Last Update", ""].each do |header| %>
          <%= content_tag :th, header %>  
        <%- end %>
      <%- end %>
    <%- end %>
    <%= content_tag :tbody do %>

      <%= empty_table wallets, colspan=8, no_record="No record found." %>
      <% wallets.each do |wallet| %>
        <%= content_tag :tr, id: "tr-#{wallet.address}", class: "#{wallet.validated?? nil : "inactive"}" do %>
          <%= content_tag :td, wallet.sequence, id: "td-#{wallet.address}-sequence" %>
          <%= content_tag :td, wallet.label %>
          <%= content_tag :td, wallet.address, class: "td-address" %>
          <%= content_tag :td, id: "status-#{wallet.address}-address" do %>
            <%= content_tag :span, "#{wallet.validated?? 'active' : 'inactive'}",class: "active-label label label-#{wallet.validated?? 'info' : 'default'}", title: "You can activate the wallet by deposit" %>
          <%- end %>
          <%= content_tag :td, wallet.balance_xrp.to_s, id: "td-#{wallet.address}-balance" %>
          <%= content_tag :td, wallet.pending_received_transactions_count, id: "td-#{wallet.address}-pending-received" %>
          <%= content_tag :td, time_ago_in_words(wallet.updated_at) %>
          <%= content_tag :td do %>

            <% unless wallet.deleted? %>
              <%= link_to admin_wallet_path(wallet.id, 
                modal: {
                  id: "ripples-wallet-#{wallet.id}-qr",
                  title: "",
                  template: "admin/wallets/qrcode"
                }
                ), class: 'btn btn-default', remote: true do %>
                <%= content_tag :i, "", class: 'fa fa-qrcode' %>
              <%- end%>
              
              <%= link_to admin_wallet_path(wallet.id,
                modal: {
                  id: "ripples-wallet-#{wallet.id}",
                  title: "Wallet Info",
                  template: "admin/wallets/show"
                }
                ), class: 'btn btn-default remote-modal', remote: true, title: "View QR code" do %> 
                <%= content_tag :i, "", class: 'fa fa-info' %>
              <%- end %>
              
            <%- end %>

          <%- end %>
        <%- end %>
      <%- end %>
    <%- end %>
  <%- end %>

<%= content_tag :div, class: "text-center" do %>
  <%= paginate wallets, remote: true, params: local_assigns[:pagination_path] || { controller: params[:controller], action: params[:action] } %>
  <%= content_tag :p, page_entries_info(wallets, entry_name: 'Wallets'), class: "text-right" %>
<%- end %>

app/views/admin/wallets/index.html.erb
<%= yield_content_for :page_title, "Wallets" %>

<%= box_panel use_footer: false, style: "box-primary" do |filter_box, options|%>

  <%= _content_for(filter_box, :box_panel_header) do %>
    <%= content_tag :h3, "Filter", class: "box-title" %>
    <%= box_panel_links collapse: true %>
  <%- end %>
  
  <%= _content_for(filter_box, :box_panel_body) do %>

    <%= form_tag nil, class: 'form-horizontal', method: :get, remote: true do %>

      <%= render partial: "admin/wallets/filter" %>

      <%= generate_table_input_params resources_name: "wallets", template: "admin/wallets/table", id: "table-container-for-#{controller_name}" %>
      
      <%= content_tag :div, class: "row" do %>
        <%= submit_buttons_wrapper divider: false do %>
          <%= submit_tag "Filter", class: "btn btn-info" %>
          <%= button_tag "Reset", type: "reset", class: "btn btn-default" %>
        <%- end %>
      <%- end %>

    <%- end %>
  
  <%- end %>
<%- end %>

<%= box_panel use_footer: false do |outer_template, options|%>
  <%= _content_for(outer_template, :box_panel_header) do %>
    <%= content_tag :h3, "Generated Wallets", class: "box-title" %>
    <%= box_panel_links do %>

      <%= link_to admin_wallets_path(
            table: { 
              id: "table-container-for-wallets",
              template: "admin/wallets/table",
              resources_name: "wallets"
          }), remote: true, id: "unarchived-link", class: "toggle btn btn-default", data: {toggle: "#archived-link"}, title: "Go to unarchived addresses" do %>
        <%= content_tag :i, nil, class: 'fa fa-money' %>
      <%- end %>

      <%= link_to admin_wallets_path(archived: true,
            table: 
              { 
                id: "table-container-for-wallets",
                template: "admin/wallets/table",
                resources_name: "wallets"
              }
          ), remote: true, id: "archived-link", class: "toggle btn btn-default", data: { toggle: "#unarchived-link" }, title: "Go to archived addresses" do %>
        <%= content_tag :i, nil, class: 'fa fa-archive' %>
      <%- end %>


    <%- end %>
  <%- end %>
  <%= _content_for(outer_template, :box_panel_body) do %>

    <%= box_panel body_style: "table-responsive", use_footer: false, use_header: false do |box_table, options| %>
      <%= _content_for(box_table, :box_panel_body) do %>
        <%= table_container_for collection= @wallets, resources_name: "wallets", template: "admin/wallets/table" do %>
          <%= render partial: "admin/wallets/table", locals: {wallets: @wallets}  %>
        <%- end %>
      <%- end %>
    <%- end %>
    
  
  <%- end %>
<%- end %>

app/views/admin/wallets/qrcode.html.erb
<h4 class="text-center">
  <%= @wallet.address %>
</h4>
<%= content_tag :div, class: 'container-fluid' do %>
  <%= content_tag :div, class: 'text-center' do %>
    <%= image_tag "https://chart.googleapis.com/chart?cht=qr&chl=#{@wallet.address}&chs=200x200&chld=L|0", class: 'qr-code img-thumbnail img-responsive' %>
  <%- end %>
<%- end %>

app/views/admin/wallets/show.html.erb
<%= yield_content_for :page_title, "Wallet Info" %>

<% if modal_params.present? %>

  
  <%= content_tag :table, id: "wallet-#{@wallet.address}-info", class: "table table-hover" do %>
    <%= content_tag :tr, class: 'wallet-address' do %>
      <%= content_tag :td, "Address"%>
      <%= content_tag :td, @wallet.address%>
    <%- end %>
    <%= content_tag :tr, class: 'wallet-name' do %>
      <%= content_tag :td, "Label"%>
      <%= content_tag :td, @wallet.label, style: "word-wrap: break-word;min-width: 160px;max-width: 160px;"%>
    <%- end %>
    <%= content_tag :tr, class: 'wallet-sequence' do %>
      <%= content_tag :td, "Sequence"%>
      <%= content_tag :td, nil%>
    <%- end %>
    <%= content_tag :tr, class: 'wallet-owner-count' do %>
      <%= content_tag :td, "Owner Count"%>
      <%= content_tag :td, nil%>
    <%- end %>
    <%= content_tag :tr, class: 'wallet-previousInitiatedTransactionID' do %>
      <%= content_tag :td, "previousInitiatedTransactionID"%>
      <%= content_tag :td, nil%>
    <%- end %>
    <%= content_tag :tr, class: 'wallet-previousAffectingTransactionID' do %>
      <%= content_tag :td, "PreviousAffectingTransactionID"%>
      <%= content_tag :td, nil%>
    <%- end %>
    <%= content_tag :tr, class: 'wallet-previousAffectingTransactionLedgerVersion' do %>
      <%= content_tag :td, "previousAffectingTransactionLedgerVersion"%>
      <%= content_tag :td, nil%>
    <%- end %>
    <%= content_tag :tr, class: 'wallet-xrp-balance' do %>
      <%= content_tag :td, "XRPBalance"%>
      <%= content_tag :td, nil%>
    <%- end %>
  <%- end %>

  <script type="text/javascript">
    
    $(document).ready(function(){


      var api = new ripple.RippleAPI({server:'wss://s.altnet.rippletest.net:51233'});
      var myAddress = "<%= @wallet.address %>";
      
      api.connect().then(() => {
        /* begin custom code ------------------------------------ */
        console.log('getting account info for', myAddress);
        return api.getAccountInfo(myAddress);

      }).then(info => {
        console.log(info);
        table = $("table#wallet-"+myAddress+"-info")
        table.find("tr.wallet-sequence td:last").html(info.sequence);
        table.find("tr.wallet-owner-count td:last").html(info.ownerCount);
        table.find("tr.wallet-previousInitiatedTransactionID td:last").html(info.previousInitiatedTransactionID);
        table.find("tr.wallet-previousAffectingTransactionID td:last").html(info.previousAffectingTransactionID);
        table.find("tr.wallet-previousAffectingTransactionLedgerVersion td:last").html(info.previousAffectingTransactionLedgerVersion);
        table.find("tr.wallet-xrp-balance td:last").html(info.xrpBalance);
        console.log('getAccountInfo done');

        /* end custom code -------------------------------------- */
      }).then(() => {
        return api.disconnect();
      }).then(() => {
        console.log('done and disconnected.');
      }).catch(console.error);

    })

  </script> 
<%- end %>