config/routes.rb
require 'sidekiq/web'

Rails.application.routes.draw do
  #use_doorkeeper
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html

  # sidekiq Routes
  mount Sidekiq::Web => '/sidekiq'

  # api routes
    #namespace :api do
  #  namespace :v1 do
      #
      # oauth2 implementation routes for grant password and refresh_token
      #
  #    resources :sessions, only: [:create, :update], param: :token
  #  end
  #end
  mount Api::Base => '/'

  # web socket server
  mount ActionCable.server => '/cable'

  # root path
  root to: 'home#index'

  # account's routes

  devise_for :accounts, path: 'auth', skip: [:registrations, :passwords], class_name: "Users::Models::Account",
             path_names: {sign_in: 'login', sign_out: 'logout',},
             controllers: {sessions: 'sessions',}

  # custom token login
  devise_scope :account do
    get 'sessions/token', to: "sessions#token", as: :token_session_account
  end

  namespace :ripple do
    resources :wallets do
      member do
        put :active
        put :restore
        put :secret
      end
      collection do
        unless Rails.env.production?
          post :generate_xrp_testnet_wallet
        end
      end
      resources :transactions, only: [:new, :create] do
        member do
          put :complete
        end
      end
    end
    resources :export_secrets, only: :show, path: "secrets" do
      member { put(:decrypt) }
    end
  end

  resources :plans, only: [:index], param: :name do
    resources :subscriptions, only: [:new, :create, :show], param: :name do
      member do
        put :cancel
      end
    end
  end

  resources :pins, only: [:update]

  resources :settings, path: "setting", only: [:index] do
    collection do
      put :update
    end
  end

  # static pages
  get "/pages/*page" => "pages#show", as: :page

  # admin's routes

  devise_for :admins, path: "administrator", skip: [:confirmations, :registrations], class_name: "Administration::Models::Admin",
              path_names: { sign_in: "login", sign_out:  "logout"},
              controllers: { sessions: "admin/sessions", passwords: "admin/profile" }

  namespace :admin, path: "administrator" do

    get "", to: "dashboards#index"

    resources :dashboards, path: "dashboard", only: :index do
      collection do
        get :accounts
        get :subscriptions
      end
    end
    resources :accounts, only: [:index, :show], param: :username
    resources :plans, path: "packages", param: :name do
      member do
        put :activate
        put :deactivate
      end
    end
    resources :subscriptions, only: [:index, :show], param: :name do
      member do
        put :cancel
        put :confirm
        put :expire
      end
    end

    resources :profiles, path: "profile", only: [:edit, :update]

    resources :transactions, only: [:index, :show]
    resources :wallets, only: [:index, :show]

  end


end

app/controllers/admin/subscriptions_controller.rb
module Admin
  class SubscriptionsController < AdminController
    
    self.context_resource_class= "Users::Models::Subscription"
    self.identifier = :name
    self.find_by = :name
    self.resource_actions = [:show, :cancel, :confirm, :expire]
    use_resource!

    def index
      @subscriptions = Users::Models::Subscription.filter(filter_params).page(params[:page]).per(params[:per_page] || 20)
      respond_to do |f|
        f.html
        f.js do
          render_table if table_params_present?
        end
      end
    end

    def show
      respond_to do |f|
        f.html
        f.js do 
          render_modal if modal_params_present?
        end
      end
    end

    def cancel
      if @subscription.cancel!
        message="Subscription is now canceled"
        respond_to do |f|
          f.html{ 
            flash[:notice]= message
            redirect_back(fallback_location: root_path)
          }
          f.js do 
            params[:notification]= { message: message }
            render_table "/shared/table/reload.js.erb" if table_params_present?
            render_modal if modal_params_present?
          end
        end
      end
    end

    def confirm
      if @subscription.confirm!
        message="Subscription is now activated"
        respond_to do |f|
          f.html{ 
            flash[:notice]= message
            redirect_back(fallback_location: root_path) 
          }
          f.js do 
            params[:notification]= { message: message }
            render_table "/shared/table/reload.js.erb" if table_params_present?
            render_modal if modal_params_present?
          end
        end
      end
    end

    def expire
      if @subscription.expire!
        message="Subscription is now expired"
        respond_to do |f|
          f.html{ 
            flash[:notice]= message
            redirect_back(fallback_location: root_path)
          }
          f.js do 
            params[:notification]= { message: message }
            
            render_table "/shared/table/reload.js.erb" if table_params_present?
            render_modal if modal_params_present?
          end
        end
      end
    end

  end
end

app/controllers/subscriptions_controller.rb
class SubscriptionsController < AccountController

  before_action :subscribing?, except: [:cancel, :show]

  self.resource_actions = [:new, :create, :show, :cancel]
  self.identifier = :name
  self.find_by = :name
  use_resource!

  helper_method :plan, :plan_rates

  def new
    @subscription.plan = plan
    respond_to do |f|
      f.html
      f.js
    end
  end

  def create
    if current_account.active_plan.could_be_upgraded_to?(plan)
      @subscription.plan= plan
      if @subscription.save
        respond_to do |f|
          f.html{ redirect_to plan_subscription_path(plan.name, @subscription.name) }
        end
      else
        respond_to do |f|
          f.html { render :new }
        end
      end
    else
      redirect_to plans_path, error: "Can not upgraded"
    end
  end

  def show
    
  end

  def cancel
    @subscription.cancel!
    respond_to do |f|
      f.html{ redirect_to plans_path, :notice => "Subscription is cancelled" }
    end
  end

  def resource_class_constant
    current_account.subscriptions
  end

  def subscription_params
    params[:users_models_subscription].present?? params.require(:users_models_subscription).permit(:coin) : {}
  end

  protected

    def plan
      @plan ||= Users::Models::Plan.cached_collection.find_by_name(params[:plan_name])
      @plan.present?? @plan : raise(ActiveRecord::RecordNotFound)
    end

    def plan_rates
      @plan_rates||= Users::Models::Plan.plan_rates
    end

end

app/views/subscriptions/_form.html.erb
<%= form_group subscription, :coin, { label_class: "col-sm-2", label_name: "Select Coin" } do %>
  <%= f.select :coin, plan_rates[plan.name].map{|k,v| [v.name,k] }, { prompt: "Select..." }, { required: true, class: "form-control col-sm-9", data: { rates: plan_rates[plan.name].to_json } }  %>
<%- end %>

<%= form_group subscription, :amount, { label_class: "col-sm-2" } do %>
  <%= f.text_field :amount, class: 'form-control', placeholder: 'Amount', disabled: true, required: true %>
<%- end %>

<%= form_group subscription, :price, { label_class: "col-sm-2" } do %>
  <%= f.text_field :price, class: 'form-control', value: number_to_currency(plan.price), disabled: true %>
<%- end %>


<script type="text/javascript">
  
 $(document).ready(function(){

  select = $("select#users_models_subscription_coin");
  
  rates = JSON.parse(select.attr('data-rates'));
  current_select = rates[select.val()];

  if (rates[select.val()] != undefined){
    $("input#users_models_subscription_amount").val(current_select.rate)    
  }

  $(document).on("change", "select#users_models_subscription_coin", function(e){

    rates = JSON.parse($(this).attr('data-rates'))

    current_select = rates[$(this).val()]

    $("input#users_models_subscription_amount").val(current_select.rate)

  });

 });

</script>

app/views/subscriptions/new.html.erb
<%= yield_content_for :page_title, "Upgrade or Continue Subscription" %>

<% unless Rails.env.production? %>
  <%= content_tag :div, class: 'row' do %>
    <%= content_tag :div, class: "col-md-8 col-md-offset-2" do %>
      <%= box_panel style: "box-warning box-solid" do |panel| %>

        <%= _content_for(panel, :box_panel_body) do %>
          <%= content_tag :p, "To submit payment in staging or development environment use Litecoin Testnet. Use #{link_to "litecoin testnet tool web", 'http://testnet.litecointools.com/'} to send payment".html_safe, class: "help-block", class: "text-center" %>
        <%- end %>

      <%- end %>
    <%- end %>
  <%- end %>
<%- end %>

<%= box_panel use_footer: false do |outer_template, options|%>

  <%= _content_for(outer_template, :box_panel_body) do %>
  
    <%= form_for @subscription, url: plan_subscriptions_path(plan.name), html: { class: "form form-horizontal" } do |f| %>

      <%= render partial: "subscriptions/form", locals: { f: f, plan: plan, plan_rates: plan_rates, subscription: @subscription } %>  

      <%= submit_buttons_wrapper divider: true do %>
        <%= f.submit "Continue", class: "btn btn-info" %>
        <%= link_to "Cancel", plans_path, class: "btn btn-danger"  %>
      <%- end %>

    <%- end %>

  <%- end %>

<%- end %>

app/views/subscriptions/show.html.erb
<%= yield_content_for :page_title, "Payment" %>

<%= content_tag :div, class: "row" do %>
 <%= content_tag :div, class: "col-md-6 col-md-offset-3" do %> 
  <%= box_panel do |outer_template, options|%>

    <%= _content_for(outer_template, :box_panel_header) do %>
      <%= content_tag :h4, "Upgrade or Continue #{plan.name} Plan", class: "text-center" %>
    <%- end %>

    <%= _content_for(outer_template, :box_panel_body) do %>

      <% if @subscription.qrcode_url.present? %>
        <%= content_tag :div, class: 'row' do %>
          <%= content_tag :div, class: 'text-center' do %>
            <%= image_tag @subscription.qrcode_url, class: 'qr-code img-thumbnail img-responsive' %>
          <%- end %>
        <%- end %>
      <%- end %>

    <%- end %>

    <%= _content_for outer_template, :box_panel_footer do %>

      <%= content_tag :div, class: 'well' do %>
        <%= content_tag :div, class: "text-center inner" do %>
          <%= content_tag :p, "Payment Address: <b>#{@subscription.payment_address}</b>".html_safe %>
          <%= content_tag :p, "Payment Amount: <b>#{@subscription.amount} #{@subscription.coin}</b>".html_safe %>
        <%- end %>
      <%- end %>

      <%= content_tag :div, class: "inner" do %>
        
        <% if @subscription.draft? %>
          <%= content_tag :p, "Please send the requested amount above to the shown address." %>
          <%= content_tag :p, '<font style="color:red;font-weight:bold">This transaction can not be refunded.</font>'.html_safe %>
          <%= content_tag :p do%>
            <%= content_tag :b, "This payment will Upgrade or Continue #{plan.name} Plan." %>
          <%- end %>
        <%- end %>

        <% if @subscription.waiting_confirmation? %>
        <%- end %>

        <% if @subscription.canceled? %>
        <%- end %>

        <% if @subscription.active? %>
        <%- end %>

        <% if @subscription.expired? %>

        <%- end %>

      <%- end %>

      <%= submit_buttons_wrapper divider: true do %>

        <%= link_to "Dashboard", root_path, class: "btn btn-primary" %>
        <% if true#@subscription.draft? %>
          <%= link_to "Cancel Request", cancel_plan_subscription_path(plan.name, @subscription.name), method: :put, data: { confirm: "Are you sure?", title: "Cancel Subscription Request" }, class: "btn btn-danger" %>
        <%- end %>
      <%- end %>


    <%- end %>

  <%- end %>

  <%- end %>
<%- end %>