config/routes.rb
require 'sidekiq/web'

Rails.application.routes.draw do
  #use_doorkeeper
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html

  # sidekiq Routes
  mount Sidekiq::Web => '/sidekiq'

  # api routes
    #namespace :api do
  #  namespace :v1 do
      #
      # oauth2 implementation routes for grant password and refresh_token
      #
  #    resources :sessions, only: [:create, :update], param: :token
  #  end
  #end
  mount Api::Base => '/'

  # web socket server
  mount ActionCable.server => '/cable'

  # root path
  root to: 'home#index'

  # account's routes

  devise_for :accounts, path: 'auth', skip: [:registrations, :passwords], class_name: "Users::Models::Account",
             path_names: {sign_in: 'login', sign_out: 'logout',},
             controllers: {sessions: 'sessions',}

  # custom token login
  devise_scope :account do
    get 'sessions/token', to: "sessions#token", as: :token_session_account
  end

  namespace :ripple do
    resources :wallets do
      member do
        put :active
        put :restore
        put :secret
      end
      collection do
        unless Rails.env.production?
          post :generate_xrp_testnet_wallet
        end
      end
      resources :transactions, only: [:new, :create] do
        member do
          put :complete
        end
      end
    end
    resources :export_secrets, only: :show, path: "secrets" do
      member { put(:decrypt) }
    end
  end

  resources :plans, only: [:index], param: :name do
    resources :subscriptions, only: [:new, :create, :show], param: :name do
      member do
        put :cancel
      end
    end
  end

  resources :pins, only: [:update]

  resources :settings, path: "setting", only: [:index] do
    collection do
      put :update
    end
  end

  # static pages
  get "/pages/*page" => "pages#show", as: :page

  # admin's routes

  devise_for :admins, path: "administrator", skip: [:confirmations, :registrations], class_name: "Administration::Models::Admin",
              path_names: { sign_in: "login", sign_out:  "logout"},
              controllers: { sessions: "admin/sessions", passwords: "admin/profile" }

  namespace :admin, path: "administrator" do

    get "", to: "dashboards#index"

    resources :dashboards, path: "dashboard", only: :index do
      collection do
        get :accounts
        get :subscriptions
      end
    end
    resources :accounts, only: [:index, :show], param: :username
    resources :plans, path: "packages", param: :name do
      member do
        put :activate
        put :deactivate
      end
    end
    resources :subscriptions, only: [:index, :show], param: :name do
      member do
        put :cancel
        put :confirm
        put :expire
      end
    end

    resources :profiles, path: "profile", only: [:edit, :update]

    resources :transactions, only: [:index, :show]
    resources :wallets, only: [:index, :show]

  end


end

app/controllers/admin/dashboards_controller.rb
module Admin
  class DashboardsController < AdminController
  
    def index
      
    end

    def accounts
      render json: Users::Models::Account.group_by_month(:created_at, last: 12).count
    end

    def wallets
      
    end

    def subscriptions
      render json: Users::Models::Subscription.joins(:plan).group("users_plans.name").group_by_month("users_subscriptions.created_at", last: 12).count.chart_json

    end

    def transactions
      
    end

  end
end

app/controllers/dashboard_controller.rb
class DashboardController < AccountController

  def index
    @dashboards = [1,2,3]
  end

end

app/views/admin/dashboards/index.html.erb
<%= yield_content_for :page_title, "Dashboard" %>

<%= content_tag :div, class: "row" do %>

  <%= content_tag :div, class: "col-lg-3 col-xs-6" do %>
    <%= content_tag :div, class: "small-box bg-aqua" do %>
      <%= content_tag :div, "#{content_tag :h3, Users::Models::Account.where(created_at: Time.now.beginning_of_month..Time.now.end_of_month).count} #{content_tag :p, 'New Accounts'}".html_safe, class: "inner" %>
      <%= link_to "More info #{content_tag :i, nil, class: "fa fa-arrow-circle-right"}".html_safe, admin_accounts_path(from_time: Time.now.beginning_of_month, to_time: Time.now.end_of_month), class: "small-box-footer" %>
    <%- end %>
  <%- end %>

  <%= content_tag :div, class: "col-lg-3 col-xs-6" do %>
    <%= content_tag :div, class: "small-box bg-yellow" do %>
      <%= content_tag :div, "#{content_tag :h3, Users::Models::Subscription.active.where(created_at: Time.now.beginning_of_month..Time.now.end_of_month).count} #{content_tag :p, 'New Active Subscription'}".html_safe, class: "inner" %>
      <%= link_to "More info #{content_tag :i, nil, class: "fa fa-arrow-circle-right"}".html_safe, admin_accounts_path(from_time: Time.now.beginning_of_month, to_time: Time.now.end_of_month), class: "small-box-footer" %>
    <%- end %>
  <%- end %>

  <%= content_tag :div, class: "col-lg-3 col-xs-6" do %>
    <%= content_tag :div, class: "small-box bg-green" do %>
      <%= content_tag :div, "#{content_tag :h3, Ripples::Models::Transaction.where(created_at: Time.now.beginning_of_month..Time.now.end_of_month).count} #{content_tag :p, 'New Created Transaction'}".html_safe, class: "inner" %>
      <%= link_to "More info #{content_tag :i, nil, class: "fa fa-arrow-circle-right"}".html_safe, admin_accounts_path(from_time: Time.now.beginning_of_month, to_time: Time.now.end_of_month), class: "small-box-footer" %>
    <%- end %>
  <%- end %>

  <%= content_tag :div, class: "col-lg-3 col-xs-6" do %>
    <%= content_tag :div, class: "small-box bg-red" do %>
      <%= content_tag :div, "#{content_tag :h3,Ripples::Models::Wallet.where(created_at: Time.now.beginning_of_month..Time.now.end_of_month).count} #{content_tag :p, 'New Created Wallet Address'}".html_safe, class: "inner" %>
      <%= link_to "More info #{content_tag :i, nil, class: "fa fa-arrow-circle-right"}".html_safe, admin_accounts_path(from_time: Time.now.beginning_of_month, to_time: Time.now.end_of_month), class: "small-box-footer" %>
    <%- end %>
  <%- end %>

<%- end %>


<%= content_tag :div, class: 'row' do %>
  <%= content_tag :div, class: 'col-md-6' do %>
    <%= box_panel style: "box-warning", use_footer: false, use_header: false do |accounts, options| %>
      <%= _content_for(accounts, :box_panel_body) do %>
         <%= line_chart accounts_admin_dashboards_path, title: "Accounts Charts", adapter: "highcharts", ytitle: "Registered Users", 
                      library: {
                        tooltip: {
                          pointFormat: 'Register count: <b>{point.y}</b>'
                        },
                        yAxis: {
                          allowDecimals: false
                        },
                        xAxis: {
                          xDateFormat: '%B'
                        }
                      } 
        %>
      <%- end %>
    <%- end %>
  <%- end %>

  <%= content_tag :div, class: 'col-md-6' do %>
    <%= box_panel style: "box-default", use_footer: false, use_header: false do |subscriptions, options| %>
      <%= _content_for(subscriptions, :box_panel_body) do %>
        <%= line_chart subscriptions_admin_dashboards_path, title: "Subscriptions Charts", adapter: "highcharts", ytitle: "Package Count", 
                      library: {
                        tooltip: {
                          pointFormat: 'Users count: <b>{point.y}</b>'
                        },
                        yAxis: {
                          allowDecimals: false
                        },
                        xAxis: {
                          xDateFormat: '%B'
                        }
                      } 
        %>
      <%- end %>
    <%- end %>
  <%- end %>

<%- end %>